import { useMemo, useState } from "react";
import { useAppStore } from "@/store/AppStore";
import { Empresa, Orcamento, OrcamentoItem, OrcamentoStatus, UnidadeDose } from "@/types";
import { Button } from "@/components/ui/button"; import { Card } from "@/components/ui/card"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { fmtBRL } from "@/utils/calculations"; import { toast } from "sonner";
const UNIDADES: UnidadeDose[] = ["L/ha", "mL/ha", "kg/ha", "g/ha", "ton/ha", "un/ha"]; const STATUS: OrcamentoStatus[]=["Rascunho","Enviado","Aprovado","Reprovado","Cancelado"];
const qtd=(d:number,u:UnidadeDose,a:number)=>((u==="mL/ha"||u==="g/ha")?d/1000:d)*a;
const pu=(p:number,up:string,ud:UnidadeDose)=>up==="TON"&&ud==="kg/ha"?p/1000:p;
const validade7=(data:string)=>{const d=new Date(data+"T00:00:00"); d.setDate(d.getDate()+7); return d.toISOString().slice(0,10);} ;
const nf=(n:number)=>new Intl.NumberFormat('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
export default function Orcamentos(){const {orcamentos,setOrcamentos,clientes,produtos,vendedores,empresas}=useAppStore(); const [open,setOpen]=useState(false); const [edit,setEdit]=useState<Orcamento|null>(null);
const empresaPadrao=empresas.find(e=>e.padrao&&e.ativa)?.id||empresas.find(e=>e.ativa)?.id||"";
const [form,setForm]=useState<Orcamento>({id:"",codigo:`ORC-${Date.now()}`,clienteId:"",empresaId:empresaPadrao,vendedor:"",data:new Date().toISOString().slice(0,10),validade:validade7(new Date().toISOString().slice(0,10)),status:"Rascunho",areaAplicacaoHa:0,itens:[],subtotal:0,descontoTotal:0,valorTotal:0,custoPorHectare:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
const rec=(o:Orcamento)=>{const itens=o.itens.map(i=>{const area=i.areaHa>0?i.areaHa:o.areaAplicacaoHa; const q=qtd(i.dosePorHa,i.unidadeDose,area); const v=q*pu(i.precoUnitario,i.unidadeProduto,i.unidadeDose); return {...i,areaHa:area,quantidadeTotal:q,valorTotalItem:v,custoPorHaItem:area>0?v/area:0};}); const t=itens.reduce((s,i)=>s+i.valorTotalItem,0); return {...o,itens,subtotal:t,descontoTotal:0,valorTotal:t,custoPorHectare:o.areaAplicacaoHa>0?t/o.areaAplicacaoHa:0};};
const save=()=>{if(!form.clienteId||!form.empresaId)return toast.error('Preencha cliente e empresa'); const payload=rec({...form,updatedAt:new Date().toISOString()}); setOrcamentos(p=>edit?p.map(o=>o.id===edit.id?payload:o):[{...payload,id:`orc${Date.now()}`,createdAt:new Date().toISOString()},...p]); setOpen(false);};
const print=(o:Orcamento)=>{const c=clientes.find(x=>x.id===o.clienteId); const e=empresas.find(x=>x.id===o.empresaId); const calc=rec(o); const w=window.open('','_blank'); if(!w)return; w.document.write(`<html><meta charset='utf-8'/><body><h2>ORÇAMENTO COMERCIAL</h2><p><b>Código:</b> ${o.codigo} | <b>Emissão:</b> ${o.data} | <b>Válido até:</b> ${o.validade}</p><p><b>Empresa:</b> ${e?.nomeFantasia||'-'}<br/>Razão social: ${e?.razaoSocial||'-'}<br/>CNPJ: ${e?.cnpj||'-'} IE: ${e?.inscricaoEstadual||'-'}<br/>Endereço: ${e?.endereco||'-'} ${e?.cidadeUf||''}</p><p><b>Cliente:</b> ${c?.nome||'-'} | ${c?.documento||'-'}</p><table border='1' cellspacing='0' cellpadding='4'><tr><th>Item</th><th>Produto</th><th>Dose</th><th>Área</th><th>Qtd</th><th>Preço unitário</th><th>Total</th><th>Custo/ha</th></tr>${calc.itens.map((it,idx)=>`<tr><td>${idx+1}</td><td>${it.produtoNome}</td><td>${nf(it.dosePorHa)} ${it.unidadeDose}</td><td>${nf(it.areaHa)} ha</td><td>${nf(it.quantidadeTotal)} ${it.unidadeProduto}</td><td>${fmtBRL(it.precoUnitario)}/${it.unidadeProduto}</td><td>${fmtBRL(it.valorTotalItem)}</td><td>${fmtBRL(it.custoPorHaItem)}</td></tr>`).join('')}</table><p><b>Valor total:</b> ${fmtBRL(calc.valorTotal)} | <b>Custo médio/ha:</b> ${fmtBRL(calc.custoPorHectare)}</p><p>Condições comerciais: ${o.formaPagamento||'-'} | ${o.tipoCobranca||'-'} | ${o.prazoPagamento||'-'}</p><p>Declaro estar ciente das condições comerciais apresentadas neste orçamento...</p><p>Assinatura do cliente: ______________________ Data: ___/___/____</p><p>Assinatura do consultor: _____________________ Data: ___/___/____</p></body></html>`); w.document.close(); w.print();};
return <div className='space-y-3'><Button onClick={()=>{setEdit(null); setForm({...form,id:'',itens:[],empresaId:empresaPadrao}); setOpen(true);}}>Novo orçamento</Button>{orcamentos.map(o=><Card key={o.id} className='p-3 flex gap-2'><div className='flex-1'>{o.codigo} - {fmtBRL(o.valorTotal)} - {STATUS.includes(o.status)?o.status:'Rascunho'}</div><Button size='sm' variant='outline' onClick={()=>{setEdit(o); setForm(o); setOpen(true);}}>Editar</Button><Button size='sm' onClick={()=>print(o)}>PDF</Button></Card>)}
<Dialog open={open} onOpenChange={setOpen}><DialogContent className='max-w-4xl'><DialogHeader><DialogTitle>Orçamento</DialogTitle></DialogHeader><div className='grid md:grid-cols-4 gap-2'><div><Label>Cliente</Label><Select value={form.clienteId} onValueChange={v=>setForm({...form,clienteId:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{clientes.map(c=><SelectItem key={c.id} value={c.id}>{c.nome}</SelectItem>)}</SelectContent></Select></div><div><Label>Empresa responsável</Label><Select value={form.empresaId||''} onValueChange={v=>setForm({...form,empresaId:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{empresas.filter(e=>e.ativa).map(e=><SelectItem key={e.id} value={e.id}>{e.nomeFantasia}</SelectItem>)}</SelectContent></Select></div><div><Label>Área total (ha)</Label><Input type='number' value={form.areaAplicacaoHa} onChange={e=>setForm({...form,areaAplicacaoHa:+e.target.value,itens:form.itens.map(it=>it.areaHa>0?it:{...it,areaHa:+e.target.value})})}/></div></div>
{rec(form).itens.map((it,idx)=><Card key={it.id} className='p-3'><div className='grid md:grid-cols-5 gap-2'><div><Label>Produto</Label><Select value={it.produtoId} onValueChange={v=>{const p=produtos.find(x=>x.id===v); if(!p)return; const itens=[...form.itens]; itens[idx]={...it,produtoId:p.id,produtoNome:p.nome,categoria:p.categoria,unidadeProduto:p.unidade,precoUnitario:p.precoLista}; setForm({...form,itens});}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{produtos.map(p=><SelectItem key={p.id} value={p.id}>{p.nome}</SelectItem>)}</SelectContent></Select></div><div><Label>Dose</Label><Input type='number' value={it.dosePorHa} onChange={e=>{const itens=[...form.itens];itens[idx]={...it,dosePorHa:+e.target.value};setForm({...form,itens});}}/></div><div><Label>Unidade dose</Label><Select value={it.unidadeDose} onValueChange={(v:UnidadeDose)=>{const itens=[...form.itens];itens[idx]={...it,unidadeDose:v};setForm({...form,itens});}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{UNIDADES.map(u=><SelectItem key={u} value={u}>{u}</SelectItem>)}</SelectContent></Select></div><div><Label>Área item</Label><Input type='number' value={it.areaHa} onChange={e=>{const itens=[...form.itens];itens[idx]={...it,areaHa:+e.target.value||form.areaAplicacaoHa};setForm({...form,itens});}}/></div><div><Label>Preço unitário</Label><Input type='number' value={it.precoUnitario} onChange={e=>{const itens=[...form.itens];itens[idx]={...it,precoUnitario:+e.target.value};setForm({...form,itens});}}/></div></div><div className='text-xs mt-2'>Cálculo do item: Quantidade {nf(it.quantidadeTotal)} {it.unidadeProduto} | Valor total {fmtBRL(it.valorTotalItem)} | Custo/ha {fmtBRL(it.custoPorHaItem)}</div></Card>)}
<Button variant='outline' onClick={()=>setForm({...form,itens:[...form.itens,{id:`i${Date.now()}`,produtoId:'',produtoNome:'',categoria:'',unidadeProduto:'LT',dosePorHa:0,unidadeDose:'L/ha',areaHa:form.areaAplicacaoHa,quantidadeTotal:0,precoUnitario:0,valorTotalItem:0,custoPorHaItem:0}]})}>Adicionar item</Button>
<div>Valor total: {fmtBRL(rec(form).valorTotal)}</div><DialogFooter><Button variant='outline' onClick={()=>setOpen(false)}>Cancelar</Button><Button onClick={save}>Salvar</Button></DialogFooter></DialogContent></Dialog></div>
}
