import { useMemo, useState } from "react";
import { useAppStore } from "@/store/AppStore";
import { Orcamento, OrcamentoItem, OrcamentoStatus, UnidadeDose } from "@/types";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { fmtBRL } from "@/utils/calculations";
import { toast } from "sonner";

const STATUS: OrcamentoStatus[] = ["Rascunho", "Enviado", "Aprovado", "Reprovado", "Cancelado"];
const UNIDADES: UnidadeDose[] = ["L/ha", "mL/ha", "kg/ha", "g/ha", "ton/ha", "un/ha"];
const ALL = "__all__";
type OrcamentoDisplayConfig = { key?: string; value?: boolean };

const safeDiv = (v: number, d: number) => d > 0 ? v / d : 0;
const doseNorm = (dose:number, unidade:UnidadeDose) => unidade === "mL/ha" ? dose/1000 : unidade === "g/ha" ? dose/1000 : dose;
const qtde = (dose:number, unidade:UnidadeDose, area:number) => doseNorm(dose, unidade) * area;
const precoNorm = (preco:number, unidadeProduto:string, unidadeDose:UnidadeDose) => unidadeProduto === "TON" && unidadeDose === "kg/ha" ? preco/1000 : preco;

export default function Orcamentos(){
  const { orcamentos, setOrcamentos, clientes, produtos, vendedores, ticketsMedios, setNegocios, negocios } = useAppStore();
  const showCustoConfig = ticketsMedios.find((x) => (x as OrcamentoDisplayConfig).key === "showCustoPorHectare") as OrcamentoDisplayConfig | undefined;
  const showCusto = showCustoConfig?.value ?? true;
  const [open,setOpen]=useState(false); const [edit,setEdit]=useState<Orcamento| null>(null);
  const [fCliente,setFCliente]=useState(""); const [fStatus,setFStatus]=useState("");
  const [form,setForm]=useState<Orcamento>({id:"",clienteId:"",vendedor:"",data:new Date().toISOString().slice(0,10),status:"Rascunho",areaAplicacaoHa:0,itens:[],subtotal:0,descontoTotal:0,valorTotal:0,custoPorHectare:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
  const filtered = useMemo(()=>orcamentos.filter(o=>(!fCliente||o.clienteId===fCliente)&&(!fStatus||o.status===fStatus)),[orcamentos,fCliente,fStatus]);

  const recalc=(draft:Orcamento)=>{const itens=draft.itens.map(i=>{const quantidadeTotal=qtde(i.dosePorHa,i.unidadeDose,i.areaHa);const pu=precoNorm(i.precoUnitario,i.unidadeProduto,i.unidadeDose);const valorTotalItem=quantidadeTotal*pu;return {...i,quantidadeTotal,valorTotalItem,custoPorHaItem:safeDiv(valorTotalItem,i.areaHa)};}); const subtotal=itens.reduce((s,i)=>s+i.valorTotalItem,0); const valorTotal=Math.max(0,subtotal-(draft.descontoTotal||0)); return {...draft,itens,subtotal,valorTotal,custoPorHectare:safeDiv(valorTotal,draft.areaAplicacaoHa)};};
  const save=()=>{if(!form.clienteId) return toast.error("Selecione cliente"); const payload=recalc({...form,updatedAt:new Date().toISOString()}); if(edit) setOrcamentos(p=>p.map(o=>o.id===edit.id?payload:o)); else setOrcamentos(p=>[{...payload,id:`orc${Date.now()}`,createdAt:new Date().toISOString()},...p]); setOpen(false); toast.success("Orçamento salvo");};
  const changeStatus=(o:Orcamento,status:OrcamentoStatus)=>{setOrcamentos(p=>p.map(x=>x.id===o.id?{...x,status,updatedAt:new Date().toISOString()}:x)); if(status==="Aprovado"&&o.negocioId&&window.confirm("Este orçamento foi aprovado. Deseja marcar o negócio vinculado como Fechado ganho?")){setNegocios(p=>p.map(n=>n.id===o.negocioId?{...n,status:"Fechado ganho",ultimaAtualizacao:new Date().toISOString().slice(0,10)}:n));} if(status==="Reprovado"&&o.negocioId&&window.confirm("Este orçamento foi reprovado. Deseja marcar o negócio vinculado como Fechado perdido?")){setNegocios(p=>p.map(n=>n.id===o.negocioId?{...n,status:"Fechado perdido",ultimaAtualizacao:new Date().toISOString().slice(0,10)}:n));}};

  return <div className="space-y-4"><div className="flex gap-2 flex-wrap"><Select value={fCliente || ALL} onValueChange={(v) => setFCliente(v === ALL ? "" : v)}><SelectTrigger className="w-52"><SelectValue placeholder="Filtrar cliente"/></SelectTrigger><SelectContent><SelectItem value={ALL}>Todos</SelectItem>{clientes.map(c=><SelectItem key={c.id} value={c.id}>{c.nome}</SelectItem>)}</SelectContent></Select><Select value={fStatus || ALL} onValueChange={(v) => setFStatus(v === ALL ? "" : v)}><SelectTrigger className="w-48"><SelectValue placeholder="Filtrar status"/></SelectTrigger><SelectContent><SelectItem value={ALL}>Todos</SelectItem>{STATUS.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select><Button onClick={()=>{setEdit(null); setForm({...form,id:"",clienteId:"",itens:[],descontoTotal:0,areaAplicacaoHa:0,status:"Rascunho"}); setOpen(true);}}>Novo orçamento</Button></div>
  <Card className="p-0 overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Cliente</TableHead><TableHead>Status</TableHead><TableHead>Total</TableHead><TableHead>Custo/ha</TableHead><TableHead>Ações</TableHead></TableRow></TableHeader><TableBody>{filtered.map(o=><TableRow key={o.id}><TableCell>{clientes.find(c=>c.id===o.clienteId)?.nome||"-"}</TableCell><TableCell>{o.status}</TableCell><TableCell>{fmtBRL(o.valorTotal)}</TableCell><TableCell>{fmtBRL(o.custoPorHectare)}/ha</TableCell><TableCell className="flex gap-1"><Button size="sm" variant="outline" onClick={()=>{setEdit(o); setForm(o); setOpen(true);}}>Editar orçamento</Button><Button size="sm" variant="outline" onClick={()=>window.print()}>Imprimir orçamento</Button><Select value={o.status} onValueChange={(v:OrcamentoStatus)=>changeStatus(o,v)}><SelectTrigger className="h-8 w-28"><SelectValue/></SelectTrigger><SelectContent>{STATUS.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></TableCell></TableRow>)}</TableBody></Table></Card>
  <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-4xl"><DialogHeader><DialogTitle>{edit?"Editar orçamento":"Novo orçamento"}</DialogTitle></DialogHeader><div className="grid md:grid-cols-3 gap-3"><div><Label>Cliente</Label><Select value={form.clienteId} onValueChange={v=>setForm({...form,clienteId:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{clientes.map(c=><SelectItem key={c.id} value={c.id}>{c.nome}</SelectItem>)}</SelectContent></Select></div><div><Label>Vendedor</Label><Select value={form.vendedor} onValueChange={v=>setForm({...form,vendedor:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{vendedores.map(v=><SelectItem key={v.id} value={v.nome}>{v.nome}</SelectItem>)}</SelectContent></Select></div><div><Label>Área aplicação (ha)</Label><Input type="number" value={form.areaAplicacaoHa} onChange={e=>setForm({...form,areaAplicacaoHa:+e.target.value})}/></div></div>
  <div className="space-y-2">{form.areaAplicacaoHa<=0&&<p className="text-xs text-amber-600">Informe área de aplicação para cálculo por hectare.</p>} {form.itens.map((it,idx)=><Card key={it.id} className="p-2 grid grid-cols-2 md:grid-cols-6 gap-2"><Select value={it.produtoId} onValueChange={v=>{const p=produtos.find(x=>x.id===v); if(!p) return; const n={...it,produtoId:p.id,produtoNome:p.nome,categoria:p.categoria,unidadeProduto:p.unidade,precoUnitario:p.precoLista}; const itens=[...form.itens];itens[idx]=n;setForm({...form,itens});}}><SelectTrigger><SelectValue placeholder="Produto"/></SelectTrigger><SelectContent>{produtos.map(p=><SelectItem key={p.id} value={p.id}>{p.nome}</SelectItem>)}</SelectContent></Select><Input type="number" placeholder="Dose" value={it.dosePorHa} onChange={e=>{const itens=[...form.itens];itens[idx]={...it,dosePorHa:+e.target.value};setForm({...form,itens});}}/><Select value={it.unidadeDose} onValueChange={(v:UnidadeDose)=>{const itens=[...form.itens];itens[idx]={...it,unidadeDose:v};setForm({...form,itens});}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{UNIDADES.map(u=><SelectItem key={u} value={u}>{u}</SelectItem>)}</SelectContent></Select><Input type="number" placeholder="Área" value={it.areaHa} onChange={e=>{const itens=[...form.itens];itens[idx]={...it,areaHa:+e.target.value};setForm({...form,itens});}}/><Input type="number" placeholder="Preço" value={it.precoUnitario} onChange={e=>{const itens=[...form.itens];itens[idx]={...it,precoUnitario:+e.target.value};setForm({...form,itens});}}/><Button variant="ghost" onClick={()=>setForm({...form,itens:form.itens.filter((_,i)=>i!==idx)})}>Excluir</Button></Card>)}<Button variant="outline" onClick={()=>setForm({...form,itens:[...form.itens,{id:`i${Date.now()}`,produtoId:"",produtoNome:"",categoria:"",unidadeProduto:"LT",dosePorHa:0,unidadeDose:"L/ha",areaHa:form.areaAplicacaoHa,quantidadeTotal:0,precoUnitario:0,valorTotalItem:0,custoPorHaItem:0} as OrcamentoItem]})}>Adicionar item</Button></div>
  <div className="text-sm">Subtotal: {fmtBRL(recalc(form).subtotal)} | Total: {fmtBRL(recalc(form).valorTotal)} {showCusto && <>| Custo/ha: {fmtBRL(recalc(form).custoPorHectare)}/ha</>}</div>
  <DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button onClick={save}>Gerar orçamento</Button></DialogFooter></DialogContent></Dialog></div>
}
