import { useMemo, useState } from "react";
import { useAppStore } from "@/store/AppStore";
import { DadosEmpresa, Orcamento, OrcamentoItem, OrcamentoStatus, UnidadeDose } from "@/types";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { fmtBRL } from "@/utils/calculations";
import { toast } from "sonner";
const EMPRESA_STORAGE_KEY = "safra-dados-empresa";
const STATUS: OrcamentoStatus[] = ["Rascunho", "Enviado", "Aprovado", "Reprovado", "Cancelado"];
const UNIDADES: UnidadeDose[] = ["L/ha", "mL/ha", "kg/ha", "g/ha", "ton/ha", "un/ha"];
const ALL = "__all__";
type OrcamentoDisplayConfig = { key?: string; value?: boolean };
const safeDiv = (v: number, d: number) => d > 0 ? v / d : 0;
const doseNorm = (dose:number, unidade:UnidadeDose) => unidade === "mL/ha" || unidade === "g/ha" ? dose/1000 : dose;
const qtde = (dose:number, unidade:UnidadeDose, area:number) => doseNorm(dose, unidade) * area;
const precoNorm = (preco:number, unidadeProduto:string, unidadeDose:UnidadeDose) => unidadeProduto === "TON" && unidadeDose === "kg/ha" ? preco/1000 : preco;
const fmtQtd = (v:number)=>new Intl.NumberFormat("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2}).format(v);
const slug = (v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const code = ()=>{ const d=new Date(); return `ORC-${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}-${String(d.getHours()).padStart(2,"0")}${String(d.getMinutes()).padStart(2,"0")}`; };
const validade7 = (data:string)=>{ const d=new Date(data+"T00:00:00"); d.setDate(d.getDate()+7); return d.toISOString().slice(0,10); };

export default function Orcamentos(){
  const { orcamentos, setOrcamentos, clientes, produtos, vendedores, ticketsMedios } = useAppStore();
  const showCusto = (ticketsMedios as OrcamentoDisplayConfig[]).find((x) => x.key === "showCustoPorHectare")?.value ?? true;
  const [open,setOpen]=useState(false); const [edit,setEdit]=useState<Orcamento| null>(null);
  const [fCliente,setFCliente]=useState(""); const [fStatus,setFStatus]=useState("");
  const [form,setForm]=useState<Orcamento>({id:"",codigo:code(),clienteId:"",vendedor:"",data:new Date().toISOString().slice(0,10),validade:validade7(new Date().toISOString().slice(0,10)),status:"Rascunho",areaAplicacaoHa:0,itens:[],subtotal:0,descontoTotal:0,valorTotal:0,custoPorHectare:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
  const filtered = useMemo(()=>orcamentos.filter(o=>(!fCliente||o.clienteId===fCliente)&&(!fStatus||o.status===fStatus)),[orcamentos,fCliente,fStatus]);
  const recalc=(draft:Orcamento)=>{const itens=draft.itens.map(i=>{const quantidadeTotal=qtde(i.dosePorHa,i.unidadeDose,i.areaHa);const pu=precoNorm(i.precoUnitario,i.unidadeProduto,i.unidadeDose);const valorTotalItem=quantidadeTotal*pu;return {...i,quantidadeTotal,valorTotalItem,custoPorHaItem:safeDiv(valorTotalItem,i.areaHa)};}); const subtotal=itens.reduce((s,i)=>s+i.valorTotalItem,0); const valorTotal=subtotal; return {...draft,itens,subtotal,descontoTotal:0,valorTotal,custoPorHectare:safeDiv(valorTotal,draft.areaAplicacaoHa)};};
  const save=()=>{if(!form.clienteId) return toast.error("Selecione cliente"); const payload=recalc({...form,validade:form.validade||validade7(form.data),updatedAt:new Date().toISOString()}); if(edit) setOrcamentos(p=>p.map(o=>o.id===edit.id?payload:o)); else setOrcamentos(p=>[{...payload,id:`orc${Date.now()}`,createdAt:new Date().toISOString()},...p]); setOpen(false); toast.success("Orçamento salvo");};
  const exportPdf=(orcamento:Orcamento)=>{ const clienteObj = clientes.find(c=>c.id===orcamento.clienteId); const cliente = clienteObj?.nome || "cliente"; const empresa:DadosEmpresa = JSON.parse(localStorage.getItem(EMPRESA_STORAGE_KEY) || '{"id":"empresa-default"}'); const calculado = recalc(orcamento);
  const lines:string[]=[]; const line=(t:string)=>lines.push(t);
  line(`ORÇAMENTO COMERCIAL - ${orcamento.codigo}`); line(`Empresa: ${empresa.nomeFantasia || "Empresa não configurada"}`); line(`Razão social: ${empresa.razaoSocial || "-"}`); line(`CNPJ: ${empresa.cnpj || "-"} | IE: ${empresa.inscricaoEstadual || "-"}`); line(`Endereço: ${empresa.endereco || "-"} - ${empresa.cidadeUf || "-"}`); line(`Telefone: ${empresa.telefone || "-"} | E-mail: ${empresa.email || "-"}`); line(`Consultor responsável: ${orcamento.vendedor || empresa.consultorPadrao || "-"}`); line(`Data de emissão: ${orcamento.data} | Válido até: ${orcamento.validade || validade7(orcamento.data)}`);
  line(`Cliente: ${clienteObj?.nome || "-"} | CPF/CNPJ: ${clienteObj?.documento || "-"} | IE: ${clienteObj?.inscricaoEstadual || "-"}`); line(`Endereço cliente: ${clienteObj?.endereco || "-"} | Cidade/UF: ${clienteObj?.cidade || "-"}`); line(`Contato: ${clienteObj?.nomeContato || "-"} | Telefone: ${clienteObj?.telefone || "-"} | E-mail: ${clienteObj?.email || "-"}`); line(`Cultura principal: ${clienteObj?.culturaPrincipal || clienteObj?.culturas || "-"} | Área aplicação/potencial: ${clienteObj?.areaAplicacaoPotencial || "-"}`);
  line("Itens:"); calculado.itens.forEach((it,idx)=>{ line(`${idx+1}. Produto: ${it.produtoNome} | Linha/Categoria: ${it.categoria} | Unidade: ${it.unidadeProduto}`); line(`Dose por hectare: ${fmtQtd(it.dosePorHa)} ${it.unidadeDose} | Área aplicada: ${fmtQtd(it.areaHa)} ha | Quantidade total: ${fmtQtd(it.quantidadeTotal)}`); line(`Preço unitário: ${fmtBRL(precoNorm(it.precoUnitario,it.unidadeProduto,it.unidadeDose))} | Valor total: ${fmtBRL(it.valorTotalItem)}`); if(showCusto) line(`Custo por hectare: ${fmtBRL(it.custoPorHaItem)}/ha`); });
  line(`Valor total do orçamento: ${fmtBRL(calculado.valorTotal)}`); if(showCusto) line(`Custo médio por hectare: ${fmtBRL(calculado.custoPorHectare)}/ha`); line("Condições comerciais:"); line(`Forma de pagamento: ${orcamento.formaPagamento || "-"}`); line(`Tipo de cobrança: ${orcamento.tipoCobranca || "-"}`); line(`Prazo de pagamento: ${orcamento.prazoPagamento || "-"}`); line(`Observações comerciais: ${orcamento.observacoes || empresa.observacoesComerciaisPadrao || "-"}`);
  line("Aceite: Declaro estar ciente das condições comerciais apresentadas neste orçamento."); line("A aprovação deste documento autoriza o consultor a encaminhar a negociação para a empresa responsável pelo faturamento."); line("Este orçamento não substitui pedido formal, nota fiscal, receituário agronômico ou demais documentos exigidos pela legislação aplicável."); line("Orçamento válido por 7 dias a partir da data de emissão. Valores sujeitos à disponibilidade de estoque e confirmação comercial pela empresa."); line("Aplicações e recomendações técnicas devem seguir orientação profissional e legislação vigente.");
  line("Assinatura do cliente: ____________________  Nome: ____________________ CPF/CNPJ: ____________________ Data: ____/____/______"); line("Assinatura do consultor: __________________ Nome: ____________________ Data: ____/____/______");
  const escapePdf = (text: string) => text.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
  const content = ["BT","/F1 9 Tf","40 800 Td",...lines.map((l)=>`(${escapePdf(l)}) Tj\n0 -13 Td`),"ET"].join("\n");
  const pdf = `%PDF-1.3\n1 0 obj<< /Type /Catalog /Pages 2 0 R >>endobj\n2 0 obj<< /Type /Pages /Kids [3 0 R] /Count 1 >>endobj\n3 0 obj<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>endobj\n4 0 obj<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>endobj\n5 0 obj<< /Length ${content.length} >>stream\n${content}\nendstream\nendobj\nxref\n0 6\n0000000000 65535 f \n0000000010 00000 n \n0000000060 00000 n \n0000000117 00000 n \n0000000243 00000 n \n0000000313 00000 n \ntrailer<< /Root 1 0 R /Size 6 >>\nstartxref\n${350 + content.length}\n%%EOF`;
  const blob = new Blob([pdf], { type: "application/pdf" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `orcamento-${slug(cliente)}-${orcamento.codigo}.pdf`; a.click(); URL.revokeObjectURL(url);
  };

  return <div className="space-y-4"><div className="flex gap-2 flex-wrap"><Select value={fCliente || ALL} onValueChange={(v) => setFCliente(v === ALL ? "" : v)}><SelectTrigger className="w-52"><SelectValue placeholder="Filtrar cliente"/></SelectTrigger><SelectContent><SelectItem value={ALL}>Todos</SelectItem>{clientes.map(c=><SelectItem key={c.id} value={c.id}>{c.nome}</SelectItem>)}</SelectContent></Select><Select value={fStatus || ALL} onValueChange={(v) => setFStatus(v === ALL ? "" : v)}><SelectTrigger className="w-48"><SelectValue placeholder="Filtrar status"/></SelectTrigger><SelectContent><SelectItem value={ALL}>Todos</SelectItem>{STATUS.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select><Button onClick={()=>{setEdit(null); const d=new Date().toISOString().slice(0,10); setForm({...form,id:"",codigo:code(),clienteId:"",itens:[],descontoTotal:0,areaAplicacaoHa:0,status:"Rascunho",data:d,validade:validade7(d)}); setOpen(true);}}>Novo orçamento</Button></div>
  <Card className="p-0 overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Código</TableHead><TableHead>Cliente</TableHead><TableHead>Status</TableHead><TableHead>Validade</TableHead><TableHead>Total</TableHead><TableHead>Ações</TableHead></TableRow></TableHeader><TableBody>{filtered.map(o=><TableRow key={o.id}><TableCell>{o.codigo}</TableCell><TableCell>{clientes.find(c=>c.id===o.clienteId)?.nome||"-"}</TableCell><TableCell>{o.status}</TableCell><TableCell>{o.validade||validade7(o.data)}</TableCell><TableCell>{fmtBRL(o.valorTotal)}</TableCell><TableCell className="flex gap-1"><Button size="sm" variant="outline" onClick={()=>{setEdit(o); setForm({...o, codigo:o.codigo || code(), validade:o.validade || validade7(o.data)}); setOpen(true);}}>Editar orçamento</Button><Button size="sm" onClick={()=>exportPdf(o)}>Gerar PDF</Button></TableCell></TableRow>)}</TableBody></Table></Card>
  <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-4xl"><DialogHeader><DialogTitle>{edit?"Editar orçamento":"Novo orçamento"}</DialogTitle></DialogHeader><div className="grid md:grid-cols-4 gap-3"><div><Label>Cliente</Label><Select value={form.clienteId} onValueChange={v=>setForm({...form,clienteId:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{clientes.map(c=><SelectItem key={c.id} value={c.id}>{c.nome}</SelectItem>)}</SelectContent></Select></div><div><Label>Consultor</Label><Select value={form.vendedor} onValueChange={v=>setForm({...form,vendedor:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{vendedores.map(v=><SelectItem key={v.id} value={v.nome}>{v.nome}</SelectItem>)}</SelectContent></Select></div><div><Label>Código</Label><Input value={form.codigo} onChange={e=>setForm({...form,codigo:e.target.value})}/></div><div><Label>Validade</Label><Input type="date" value={form.validade || ""} onChange={e=>setForm({...form,validade:e.target.value})}/></div></div>
  <div className="space-y-2">{recalc(form).itens.map((it,idx)=><Card key={it.id} className="p-3"><div className="grid md:grid-cols-3 gap-2"><div><Label>Produto</Label><Select value={it.produtoId} onValueChange={v=>{const p=produtos.find(x=>x.id===v); if(!p) return; const itens=[...form.itens];itens[idx]={...it,produtoId:p.id,produtoNome:p.nome,categoria:p.categoria,unidadeProduto:p.unidade,precoUnitario:p.precoLista};setForm({...form,itens});}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{produtos.map(p=><SelectItem key={p.id} value={p.id}>{p.nome}</SelectItem>)}</SelectContent></Select></div><div><Label>Dose por hectare</Label><Input type="number" value={it.dosePorHa} onChange={e=>{const itens=[...form.itens];itens[idx]={...it,dosePorHa:+e.target.value};setForm({...form,itens});}}/></div><div><Label>Unidade da dose</Label><Select value={it.unidadeDose} onValueChange={(v:UnidadeDose)=>{const itens=[...form.itens];itens[idx]={...it,unidadeDose:v};setForm({...form,itens});}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{UNIDADES.map(u=><SelectItem key={u} value={u}>{u}</SelectItem>)}</SelectContent></Select></div></div></Card>)}<Button variant="outline" onClick={()=>setForm({...form,itens:[...form.itens,{id:`i${Date.now()}`,produtoId:"",produtoNome:"",categoria:"",unidadeProduto:"LT",dosePorHa:0,unidadeDose:"L/ha",areaHa:form.areaAplicacaoHa,quantidadeTotal:0,precoUnitario:0,valorTotalItem:0,custoPorHaItem:0} as OrcamentoItem]})}>Adicionar item</Button></div>
  <div className="text-sm"><p>Valor total do orçamento: {fmtBRL(recalc(form).valorTotal)}</p>{showCusto && <p>Custo médio por hectare: {fmtBRL(recalc(form).custoPorHectare)}/ha</p>}</div>
  <DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button onClick={save}>Salvar orçamento</Button></DialogFooter></DialogContent></Dialog></div>
}
